// <auto-generated />
using System;
using IntegrationServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integration_Services.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20261002182503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrationServices.Entities.BCPurchaseInvoice", b =>
                {
                    b.Property<Guid>("BCPurchaseInvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountIncludingVAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTermsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorInvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCPurchaseInvoiceID");

                    b.HasIndex("DueDate");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("PostingDate");

                    b.HasIndex("PurchaseOrderNo");

                    b.HasIndex("VendorNo");

                    b.ToTable("BCPurchaseInvoices");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCPurchaseInvoiceLine", b =>
                {
                    b.Property<Guid>("BCPurchaseInvoiceLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LineAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCPurchaseInvoiceLineID");

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("PostingDate");

                    b.HasIndex("VendorNo");

                    b.HasIndex("InvoiceNo", "LineNo")
                        .IsUnique();

                    b.ToTable("BCPurchaseInvoiceLines");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCPurchaseOrder", b =>
                {
                    b.Property<Guid>("BCPurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountIncludingVAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTermsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCPurchaseOrderID");

                    b.HasIndex("ExpectedReceiptDate");

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("OrderDate");

                    b.HasIndex("PurchaseOrderNo")
                        .IsUnique();

                    b.HasIndex("VendorNo");

                    b.ToTable("BCPurchaseOrders");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCPurchaseOrderLine", b =>
                {
                    b.Property<Guid>("BCPurchaseOrderLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LineAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OutstandingQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PlannedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PromisedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityInvoiced")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityReceived")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("RequestedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCPurchaseOrderLineID");

                    b.HasIndex("ExpectedReceiptDate");

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("VendorNo");

                    b.HasIndex("PurchaseOrderNo", "LineNo")
                        .IsUnique();

                    b.ToTable("BCPurchaseOrderLines");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCPurchaseReceipt", b =>
                {
                    b.Property<Guid>("BCPurchaseReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCPurchaseReceiptID");

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("PostingDate");

                    b.HasIndex("PurchaseOrderNo");

                    b.HasIndex("ReceiptNo")
                        .IsUnique();

                    b.HasIndex("VendorNo");

                    b.ToTable("BCPurchaseReceipts");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCPurchaseReceiptLine", b =>
                {
                    b.Property<Guid>("BCPurchaseReceiptLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyFromVendorNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DirectUnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpectedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayToVendorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PromisedReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PurchaseOrderLineNo")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseOrderNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityInvoiced")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QuantityReceivedNotInvoiced")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitCostLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorShipmentNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BCPurchaseReceiptLineID");

                    b.HasIndex("BuyFromVendorNo");

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("PostingDate");

                    b.HasIndex("PurchaseOrderNo");

                    b.HasIndex("ReceiptNo", "LineNo")
                        .IsUnique();

                    b.ToTable("BCPurchaseReceiptLines");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCVendor", b =>
                {
                    b.Property<Guid>("BCVendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BalanceLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Blocked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryRegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCVendorID");

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("VendorNo")
                        .IsUnique();

                    b.ToTable("BCVendors");
                });

            modelBuilder.Entity("IntegrationServices.Entities.BCVendorLedgerEntry", b =>
                {
                    b.Property<Guid>("BCVendorLedgerEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AppliesToDocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppliesToDocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CreditAmountLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DebitAmountLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryNo")
                        .HasColumnType("int");

                    b.Property<string>("GlobalDimension1Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalDimension2Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Open")
                        .HasColumnType("bit");

                    b.Property<decimal?>("OriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OriginalAmountLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDiscountDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RemainingAmountLCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BCVendorLedgerEntryID");

                    b.HasIndex("DocumentNo");

                    b.HasIndex("DueDate");

                    b.HasIndex("EntryNo")
                        .IsUnique();

                    b.HasIndex("LastModifiedDateTime");

                    b.HasIndex("Open");

                    b.HasIndex("PostingDate");

                    b.HasIndex("VendorNo");

                    b.ToTable("BCVendorLedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
